/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/common/backtop/BackTop.vue')['default']
    GoodsList: typeof import('./src/components/content/goods/GoodsList.vue')['default']
    GoodsListItem: typeof import('./src/components/content/goods/GoodsListItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./src/components/common/navbar/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabControl: typeof import('./src/components/content/tabControl/TabControl.vue')['default']
    VanAddressEdit: typeof import('vant/es')['AddressEdit']
    VanAddressList: typeof import('vant/es')['AddressList']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanPopup: typeof import('vant/es')['Popup']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
